- name: Install chromium packages
  apt:
    pkg: chromium
- name: Install browser kiosk service
  template:
    src: browser.service
    dest: /etc/systemd/system/browser.service
- name: Create chromium policies directory
  file:
    path: /etc/chromium/policies
    state: directory
    mode: 0755
    owner: root
    group: root
- name: Create chromium managed policies directory
  file:
    path: /etc/chromium/policies/managed
    state: directory
    mode: 0755
    owner: root
    group: root
- name: Install browser policies
  template:
    src: kiosk.json
    dest: /etc/chromium/policies/managed/kiosk.json
- name: Enable browser kiosk service
  ansible.builtin.systemd:
    name: browser.service
    enabled: yes
    masked: no
    daemon_reload: true
    state: started
