- name: Get encrypted GRUB password
  shell:
    echo -e '{{ grub_passwd }}\n{{ grub_passwd }}' | grub-mkpasswd-pbkdf2 |tail -n 1 | sed 's/^.*is //'
  register: grub_passwd_enc
- name: Install GRUB security
  template:
    src: grub.cfg
    dest: /etc/grub.d/000_password
  notify: Update GRUB config
- name: Disable bootloader menu
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: GRUB_TIMEOUT=0
    regexp: "^GRUB_TIMEOUT"
  notify: Update GRUB config
- name: Quiet GRUB boot
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3"'
    regexp: "^GRUB_CMDLINE.*"
  notify: Update GRUB config
- name: Create kiosk user
  ansible.builtin.user:
    name: "{{ kiosk_user }}"
- name: Create kiosk user config directory
  ansible.builtin.file:
    path: "/home/{{ kiosk_user }}/.config"
    state: directory
    owner: "{{ kiosk_user }}"
    mode: 0750
- name: Disable local consoles
  ansible.builtin.lineinfile:
    path: /etc/default/console-setup
    line: 'ACTIVE_CONSOLES=""'
    regexp: "^ACTIVE_CONSOLES.*"
